version: "3.9"

services:
  backend:
    container_name: "test-api-oprec"
    image: "oprec-api-test"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bunx prima generate && bun run --watch src/index.ts'"
    volumes: ["./:/home/bun/app"]
    restart: unless-stopped
    networks:
      - cf-tunnel

networks:
  cf-tunnel:
    external: true
