version: "3.9"

services:
  backend:
    container_name: "test-api-oprec"
    image: "oprec-api-test"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bunx prisma generate && bun run --watch src/index.ts'"
    volumes: ["./:/home/bun/app"]
    restart: unless-stopped
    networks:
      - cf-tunnel

  frontend:
    container_name: "test-oprec"
    image: "oprec-test"
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - cf-tunnel

networks:
  cf-tunnel:
    external: true
