version: "3.9"

services:
  backend:
    image: "oprec-api-test"
    volumes: ["./:/home/bun/app"]
    restart: unless-stopped
    networks:
      - cf-tunnel

networks:
  cf-tunnel:
    external: true
